config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'dashboard', to: 'pages#dashboard', as: :dashboard
  resources :babies, only: [:show, :new, :create, :edit, :update, :destroy] do
  	resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/baby.rb
class Baby < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :user
  has_many :bookings, dependent: :destroy
  validates :first_name, presence: { message: "Enter a cutie name for your cutie baby" }, format: { with: /[a-zA-Z]/ }
  validates :title, presence: { message: "Enter a cutie nickname for your cutie baby" }, format: { with: /[a-zA-Z]/ }
  validates :gender, presence: { message: "Your baby can be a male a female or ?" }, inclusion: { in: ["boy", "girl", "other?"] }
  validates :description, presence: { message: "Please enter at least 10 characters :)" }, length: { minimum: 10 }
  validates :age, presence: true
  validates :price_per_day, presence: { message: "Enter a number, don't be greedy but don't be cheap either, you are renting your baby ffs" }
  validates :photo, presence: { message: "Please put a pic of your cutie baby" }
  validates_numericality_of :price_per_day
  
  include PgSearch
  pg_search_scope :global_search,
    against: [ :description, :title],
    associated_against: {
      user: [ :address]
    },
    using: {
      tsearch: { prefix: true }
    }

  def self.geocoded
    select { |baby| baby.user.geocoded? }
  end

  def available?(from_date, to_date)
    bookings.where(start_date: from_date..to_date).or(bookings.where(end_date: from_date..to_date)).blank?
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :baby
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :price, presence: true
  validate :end_date_cannot_be_lower_than_start_date
  validate :baby_available?

  def baby_available?
    errors.add(:start_date, "Baby is already taken at these dates") unless baby.available?(start_date, end_date)
  end

  def end_date_cannot_be_lower_than_start_date
    if start_date > end_date
      errors.add(:end_date, "can't be before starting date")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :photo, PhotoUploader
  validates :photo, presence: true
  has_many :babies, dependent: :destroy
  has_many :bookings, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action.'
    redirect_to(root_path)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :address, :description, :pedophile, :photo])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :address, :description, :photo])
  end


  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/babies_controller.rb
class BabiesController < ApplicationController
  before_action :set_baby, only: [:show, :edit, :update, :destroy]

  def show
  	@booking = Booking.new
  end

  def new
    @baby = Baby.new
    authorize @baby
  end

  def create
    @baby = Baby.new(babies_params)
    authorize @baby
    @baby.user = current_user
    if @baby.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @baby.update(babies_params)
    redirect_to baby_path(@baby)
  end

  def destroy
    @baby.destroy
    redirect_to dashboard_path, notice: "Your baby has successfully been deleted !"
  end

  private

  def set_baby
    @baby = Baby.find(params[:id])
    authorize @baby
  end

  def babies_params
    params.require(:baby).permit(:first_name, :photo, :age, :gender, :description, :price_per_day, :clean, :sleepy, :excited, :crying, :fat, :playful, :funny, :public, :animals, :speaks, :title, :photo)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
  	@booking = Booking.new(bookings_params)
  	authorize @booking
  	@baby = Baby.find(params[:baby_id])
  	@booking.user = current_user
  	@booking.baby = @baby
  	@booking.price = @baby.price_per_day * (((@booking.end_date - @booking.start_date) / 86_400) + 1)

  	if @booking.save
      redirect_to dashboard_path
    else
      render 'babies/show'
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.destroy
    redirect_to dashboard_path
  end

  private

  def bookings_params
    params.require(:booking).permit(:start_date, :end_date, :price)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @babies = policy_scope(Baby)
    @babies = @babies.global_search(params[:query]) if params[:query].present?
    @babies = @babies.where("age >= :min_age AND age <= :max_age", min_age: params[:min_age], max_age: params[:max_age]) if params[:min_age].present? && params[:max_age].present?
    @babies = @babies.where("price_per_day >= :min_price AND price_per_day <= :max_price", min_price: params[:min_price], max_price: params[:max_price]) if params[:min_price].present? && params[:max_price].present?
    @babies = @babies.where(clean: true) if params[:clean].present?
    @babies = @babies.where(sleepy: true) if params[:sleepy].present?
    @babies = @babies.where(excited: true) if params[:excited].present?
    @babies = @babies.where(crying: true) if params[:crying].present?
    @babies = @babies.where(fat: true) if params[:fat].present?
    @babies = @babies.where(playful: true) if params[:playful].present?
    @babies = @babies.where(funny: true) if params[:funny].present?
    @babies = @babies.where(public: true) if params[:public].present?
    @babies = @babies.where(animals: true) if params[:animals].present?
    @babies = @babies.where(speaks: true) if params[:speaks].present?
    @babies = @babies.geocoded

    @markers = @babies.map do |baby|
      {
        lat: baby.user.latitude,
        lng: baby.user.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { baby: baby }),
        image_url: helpers.asset_url('baby-carriage-solid.svg')
      }
    end
  end

  def global_search
  end

  def dashboard
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/babies/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-xs-12 col-sm-6 mt-4">
      <%= simple_form_for(baby) do |f| %>
      <%= f.input :first_name %>
      <%= f.input :title %>
      <%= f.input :age, collection: ["0", "1", "2", "3"], include_blank: false %>
      <%= f.input :gender, collection: ["boy", "girl", "other?"], include_blank: false %>
      <%= f.input :description %>
      <%= f.input :price_per_day %>
      <%= f.input :clean, as: :boolean %>
      <%= f.input :sleepy, as: :boolean %>
      <%= f.input :excited, as: :boolean %>
      <%= f.input :crying, as: :boolean %>
      <%= f.input :fat, as: :boolean %>
      <%= f.input :playful, as: :boolean %>
      <%= f.input :funny, as: :boolean %>
      <%= f.input :public, as: :boolean %>
      <%= f.input :animals, as: :boolean %>
      <%= f.input :speaks, as: :boolean %>
      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>
      <button class="btn button"><% f.button :submit%>Create a Baby</button>
      <% end %>
    </div>
  </div>
</div>

app/views/babies/edit.html.erb
<%= render 'form', baby: @baby %>

app/views/babies/new.html.erb
<%= simple_form_for(@baby) do |f| %>
<%= f.input :first_name %>
<%= f.input :title %>
<%= f.input :age, collection: ["0", "1", "2", "3"], include_blank: false %>
<%= f.input :gender, collection: ["boy", "girl", "other?"], include_blank: false %>
<%= f.input :description %>
<%= f.input :price_per_day %>
<%= f.input :clean, as: :boolean %>
<%= f.input :sleepy, as: :boolean %>
<%= f.input :excited, as: :boolean %>
<%= f.input :crying, as: :boolean %>
<%= f.input :fat, as: :boolean %>
<%= f.input :playful, as: :boolean %>
<%= f.input :funny, as: :boolean %>
<%= f.input :public, as: :boolean %>
<%= f.input :animals, as: :boolean %>
<%= f.input :speaks, as: :boolean %>
<%= f.input :photo %>
<%= f.input :photo_cache, as: :hidden %>
<%= f.submit %>

<% end %>

app/views/babies/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-xl-8">
	     <div class="row card-show-head">
           <div class="baby-img">
    		      <%= cl_image_tag @baby.photo, height: 250, width: 250, crop: :fill %>
    	     </div>
    	     <div class="col-6">
             <div class="baby-info p-2">
            		<h1><%= @baby.first_name %> - <%= @baby.title %></h1>
            		<h2><%= @baby.age %> years old</h2>
      	     </div>
             <div class="baby-price">
              <h2><%= @baby.price_per_day %> €</h2>
             </div>
           </div>
          </div>
         <div class="row card-show-details">
           <div class ="col">
             <div class="baby-traits p-3">
              <h2>My baby skills</h2>
              <ul>
                <% if @baby.clean %>
                  <li>Clean</li>
                <% end %>
                <% if @baby.sleepy %>
                  <li>Sleepy</li>
                <% end %>
                <% if @baby.excited %>
                  <li>Excited</li>
                <% end %>
                <% if @baby.crying %>
                  <li>Cries a lot</li>
                <% end %>
                <% if @baby.fat %>
                  <li>Fat</li>
                <% end %>
                <% if @baby.playful %>
                  <li>Playful</li>
                <% end %>
                <% if @baby.funny %>
                  <li>Funny</li>
                <% end %>
                <% if @baby.public %>
                  <li>At ease in public</li>
                <% end %>
                <% if @baby.animals %>
                  <li>At ease with animals</li>
                <% end %>
                <% if @baby.speaks %>
                  <li>Speaks</li>
                <% end %>
              </ul>
              <p>
                <% if policy(@baby).edit? %>
                <%= link_to "Edit my baby", edit_baby_path(@baby) %>
                <% end %>
              </p>
              <p>
                <% if policy(@baby).destroy? %>
                <%= link_to "Delete my baby", baby_path(@baby),
                method: :delete,
                data: { confirm: "Are you sure?" } %>
                <% end %>
              </p>
            </div>
          </div>
          <div class="col align-items-center">
             <div class="baby-description p-3">
                "<%= @baby.description %>"
             </div>
           </div>
         </div>
  	     
      </div>

    <div class="col-xs-12 col-xl-4">
      <div class="form-container">
        <div class="header">
          <div class="header-row">
            <div class="big-bold" id="price" data-amount-cents="<%= @baby.price_per_day * 100 %>"><%= @baby.price_per_day %>€</div>
            <div class="small-light"> / Day</div>
          </div>
        </div>

  <%= simple_form_for([@baby, @booking]) do |f| %>
  <%= f.input :start_date, as: :date, html5: true %>
  <%= f.input :end_date, as: :date, disabled: true, html5: true %>
  <%= f.input :price, disabled: true, :as => :hidden, input_html: {value: @baby.price_per_day} %>
  <%= f.submit "Book for #{@baby.price_per_day}€", id: "submit", class: "btn button" %>
  <% end %>
  </div>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>AirBaby</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_pack_tag 'application', media: 'all' %>
</head>
<body>
  <div class="page">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </div>
  <%= render 'shared/footer' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
</body>
</html>

app/views/pages/_info_window.html.erb
<h4><%= baby.price_per_day %>€</h4>
<h2><%= baby.first_name.capitalize %></h2>
<h4>„<%=baby.description %>“</h4>

app/views/pages/dashboard.html.erb
<div class="container">
  <h1>My Babies</h1>
  <div class="row justify-center">
    <div class="row col-7">
      <ul class="dashboard-container">
        <% current_user.babies.each do |baby| %>
        <div class="card-product mt-4">
          <%= cl_image_tag baby.photo, height: 180, width: 180, crop: :fill %>
          <div class="card-product-infos">
            <h3><%= baby.first_name %></h3>
            <h2><%= baby.title %></h2>
            <p><%= baby.description %></p>
            <h3><%= baby.price_per_day %> € / per day</h3>
            <div class="d-flex">
              <%= button_to "See my baby", baby_path(baby), :class => "btn button mr-2", :method => :get %>
              <%= button_to "Edit my baby", edit_baby_path(baby), :class => "btn button mr-2", :method => :get %>
              <%= button_to "Delete my baby", baby_path(baby),
              :class => "btn button mr-2",
              method: :delete,
              data: { confirm: "Are you sure?" } %>
              </div>
            </div>
          <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#baby<%= baby.id %>" aria-expanded="false" aria-controls="collapseExample">
            Voir ses bookings
            <br><i class="far fa-arrow-alt-circle-right"></i>
          </button>
          </div>
          <% end %>
        </ul>
      </div>
      <div class="row col-5">
        <% current_user.babies.each do |baby| %>
          <div class="collapse ml-2" id="baby<%= baby.id %>">
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= baby.photo %>)">
            <%= baby.first_name %>'s Reservations
          </div>

          <div class="notification" id="details-<%=  baby.id %>" >
            <h2 class="notification-content">Total Booking : <%= baby.bookings.length %> |
            <% price = [] %>
            <% baby.bookings.each do |booking| %>
            <% price << booking.price %>
            <% end %>
            <strong><%= price.inject(0){|sum,x| sum + x } %> € </strong></h2>
          </div>

          <% baby.bookings.each do |booking| %>
          <div class="notification">
            <img src='<%= User.find(booking.user_id).photo %>' class="avatar-large" />
            <div class="notification-content">
              <p>Rented by : <%= User.find(booking.user_id).username %></p>
              <p><small>From : <%= booking.start_date.to_date %></small>
                <i class="fas fa-long-arrow-alt-right"></i>
                <small>To : <%= booking.end_date.to_date %></small></p>

                <p>Duration : <strong><%= (((booking.end_date - booking.start_date)/86400) + 1).to_i %> days</strong> | Total price : <%= booking.price %> €</p>
              </div>
            </div>
              <% end %>

          </div>
        <% end %>

      </div>

  </div>



      <h1>My booked babies</h1>
      <div class="row justify-center">
        <div class="row">
          <ul>
            <% current_user.bookings.each do |booking| %>
            <%= link_to(baby_path(booking.baby)) do %>
            <div class="card-product mt-4">
              <%= cl_image_tag booking.baby.photo, height: 180, width: 180, crop: :fill %>
              <div class="card-product-infos">
                <h2><%= booking.baby.title %></h2>
                <h3><%= booking.baby.first_name %></h3>
                <p><%= booking.baby.description %></p>
                <h4>Total Cost : <%= booking.price %>€</h4>
                <p><%= link_to "Delete my booking", booking_path(booking),
                method: :delete,
                data: { confirm: "Are you sure?" } %></p>
              </div>
            </div>
            <% end %>
            <% end %>
          </ul>
        </div>
      </div>
</div>

app/views/pages/home.html.erb
<% unless user_signed_in? || params[:query].present? %>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0),rgba(0,0,0,0)), url(https://images.unsplash.com/photo-1492725764893-90b379c2b6e7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80);">



  <div class="banner-card">
		<h1>Discover</h1>
		<h2> <strong>the first marketplace</strong> to <strong>rent babies</strong>!</h2>
		<p>Giving baby love to baby lovers</p>
    <p></p>
		<%= link_to "Sign-up", new_user_registration_path, class:"btn button"%>
	</div>
</div>
<% end %>


<div class="home-container">
	<div id="home-main">
    <div class="search-bar">
      <button class="btn btn-primary btn-lg btn-block" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
        Filters Babies
      </button>
      <div class="collapse" id="collapseExample">
        <div class="card card-body">
          <%= form_tag root_path, method: :get do %>
            <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Find a Baby"%>
            <%= label_tag :min_age%>
            <%= range_field_tag :min_age, params[:min_age], min: 0, max: 3, class: "form-control", value: 0%>
            <%= label_tag :max_age%>
            <%= range_field_tag :max_age, params[:max_age], min: 0, max: 3, class: "form-control", value: 3%>
            <%= text_field_tag :min_price, params[:min_price], class: "form-control", placeholder: "Price min"%>
            <%= text_field_tag :max_price, params[:max_price], class: "form-control", placeholder: "Price max"%>
            <%= label_tag :clean%>
            <%= check_box_tag :clean, params[:clean], false %>
            <%= label_tag :sleepy%>
            <%= check_box_tag :sleepy, params[:sleepy], false %>
            <%= label_tag :excited%>
            <%= check_box_tag :excited, params[:excited], false %>
            <%= label_tag :crying%>
            <%= check_box_tag :crying, params[:crying], false %>
            <%= label_tag :fat%>
            <%= check_box_tag :fat, params[:fat], false %>
            <%= label_tag :playful%>
            <%= check_box_tag :playful, params[:playful], false %>
            <%= label_tag :funny%>
            <%= check_box_tag :funny, params[:funny], false %>
            <%= label_tag :public%>
            <%= check_box_tag :public, params[:public], false %>
            <%= label_tag :animals%>
            <%= check_box_tag :animals, params[:animals], false %>
            <%= label_tag :speaks%>
            <%= check_box_tag :speaks, params[:speaks], false %>
            <%= submit_tag "Search", class: "btn button" %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="baby-cards">
      <% @babies.each do |baby| %>
        <%= link_to(baby_path(baby)) do %>
          <div class="card-product mt-4" data-center="<%= [baby.user.longitude, baby.user.latitude] %>">
            <%= cl_image_tag baby.photo, height: 180, width: 180, crop: :fill %>
            <div class="card-product-infos">
              <h3><%= baby.first_name %> | Gender: <%= baby.gender %></h3>
              <h2><%= baby.title %></h2>
              <p><%= baby.description %></p>
              <h3><%= baby.price_per_day %> € / per day</h3>
              <div class="d-flex">
              <%= button_to "See this baby", baby_path(baby), :class => "btn button mr-2", :method => :get %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

    <div
      id="map"
      class="col-sm-12 col-md-5"
      style="width: 40vw;
      height: 600px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
	<div class="footer-links">
		<a href="#"><i class="fab fa-github"></i></a>
		<a href="#"><i class="fab fa-instagram"></i></a>
	</div>
	<div class="footer-copyright">
		Babies cuteness is fun... just for one night
	</div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <%= link_to root_path, class: "navbar-brand mr-4" do  %>
      <%= image_tag("logo.png") %>
      <% end %>

   <!--  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button> -->


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto align-items-center">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Publish a baby", new_baby_path, class: "nav-link btn button mr-4" %>
        </li>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.photo, height: 56, width: 56, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Your babies", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>